version: "3.9"

services: 
    moleculerdyte:
        image: node:14
        command: ['sleep','inf']
        container_name: moleculerdyte
        volumes: 
            - .:/app
        ports: 
            - 5000:5000
        environment: 
            - DB_URL=mongodb://root:root@mongodb:27017/admin
    mongodb:
        image: mongo:latest
        restart: always
        container_name: mongodb
        ports: 
            - 27017:27017
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=root

    mongo-express:
        image: mongo-express:latest
        container_name: mongo-express
        restart: always
        ports:
            - 8081:8081
        environment:
            - ME_CONFIG_MONGODB_ADMINUSERNAME=root
            - ME_CONFIG_MONGODB_ADMINPASSWORD=root
            - ME_CONFIG_MONGODB_SERVER=mongodb
            - ME_CONFIG_MONGODB_PORT=27017

networks: 
    default:
        external: 
            name: dyte